
### End-to-end pipeline for classifying AI assitant inputs between music and directions domains

#### Written by Ruhaab Markas 

Example Playing Music:
"Play some Pantera on Spotify"

Example Directions:
"Where is the nearest Starbucks"

In [60]:

data1 = [
    "Play some music",
    "Play music",
    "Play some music",
    "Play music",
    "Play my music",
    "Play me some music",
    "Please play some music",
    "Play the music", 
    "Play my music",
    "Play some music",
    "Play music",
    "Play my music",
    "Get me directions home",
    "Take my home", 
    "How do I get home?",
    "What is the way home?",
    "Please take me home?",
    "How do I get home?",
    "What are the directons to my house?", 
    "Where is my house?", 
    "Take me to my house?",
    "Directions home",
    "Play Incubus",
    "Play Taylor Swift",
    "Play some Incubus",
    "Play some Taylor Swift",
    "Play Michael Jackson",
    "Play some Michael Jackson",
    "Play rock and roll",
    "Play some Incubus",
    "Play Alan Jackson",
    "Play some Alan Jackson", 
    "Play some music",
    "Play music",
    "Play my music",
    "Play me some music",
    "Please play some music",
    "Play the music", 
    "Play my music",
    "Play some music",
    "Play music",
    "Play my music",
    "Get me directions home",
    "Take my home", 
    "How do I get home?",
    "What is the way home?",
    "Please take me home?",
    "How do I get home?",
    "What are the directons to my house?", 
    "Where is my house?", 
    "Take me to my house?",
    "Directions home",
    "Play rock and roll",
    "Play fun music", 
    "Play my chill playlist", 
    "Play my jazz album",
    "Play some tunes",
    "Play upbeat music", 
    "Play relaxing music",
    "Play party songs",
    "Play some hip hop",
    "Take me to the mall",
    "What are the directions to the mall?",
    "Show me directions home",
    "Get me directions to the gas station",
    "How do I get home?",
    "What are the directons to my house?", 
    "Show directions home",
    "How do I get home?",
    "Give me directions home",
    "Directions home",
    "Play Incubus",
    "Play Taylor Swift",
    "Play some Incubus",
    "Play some Taylor Swift",
    "Play Michael Jackson", 
    "Play some Michael Jackson",
    "Play rock and roll",
    "Play some Incubus",
    "Play Alan Jackson",
    "Play some Alan Jackson", 
    "Take me to the mall",
    "What are the directions to the mall?",
    "Show me directions home",
    "Get me directions to the gas station",
    "How do I get home?",
    "What are the directons to my house?", 
    "Show directions home",
     "How do I get home?",
    "Give me directions home",
    "Get me directions home",
    "Take my home", 
   "How do I get home?",
   "What is the way home?",
    "Please take me home?",
    "How do I get home?",
    "What are the directons to my house?", 
   "Where is my house?", 
    "Take me to my house?",
    "Directions home",
    "Directions home",
]

In [61]:
#  check the data type to ensure it's a list
type(data1)

list

In [24]:
# Import data manipulation packages 
import pandas as pd
import numpy as np

In [82]:
# Read my offline file so that I can assign classes and labels to each index
qs = pd.read_excel('/Users/rmarkas/Desktop/Utterances.xls')
qs.head()

Utterance   Class  Label
0         Play some music      1  Music
1              Play music      1  Music
2           Play my music      1  Music
3      Play me some music      1  Music
4  Please play some music      1  Music

In [47]:
# Check the shape
qs.shape

(99, 2)

In [49]:
# Confirm that this is a dataframe
type(clean_questions)

pandas.core.frame.DataFrame

### Q1 Given the following module that outputs a vector which represents your input sentence, transform your data into numbers.

In [62]:
# Import machine learning packages
import tensorflow as tf
import tensorflow_hub as hub

# Use hub to load universal encoder and run embeddings
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/3")
embeddings = embed(data1)["outputs"]

print(embeddings)

tf.Tensor(
[[-0.03827367  0.0152842   0.09111802 ... -0.02656745  0.02676196
  -0.00693245]
 [-0.0243762   0.01918176  0.07996774 ... -0.05385037  0.02100432
   0.03922744]
 [-0.03827367  0.0152842   0.09111802 ... -0.02656745  0.02676196
  -0.00693245]
 ...
 [-0.00308145 -0.05708995  0.00261058 ... -0.00146268  0.07268234
  -0.02701968]
 [-0.02406933  0.01228792  0.00061122 ... -0.01537671  0.06456828
  -0.00335655]
 [-0.02406933  0.01228792  0.00061122 ... -0.01537671  0.06456828
  -0.00335655]], shape=(101, 512), dtype=float32)


In [63]:
# What is the shape of the embeddings matrix?
embeddings.shape

TensorShape([101, 512])

In [64]:
type(embeddings)

tensorflow.python.framework.ops.EagerTensor

In [74]:
# Process to convert embeddigns matrix into a pandas dataframe
# Step 1 create an aray
embed_array = np.array(embed_array)

In [86]:
# Step 2 convert to dataframe 
final_data = pd.DataFrame(embed_array)
final_data.head()

0         1         2         3         4         5         6    \
0 -0.038274  0.015284  0.091118  0.007086  0.020357  0.019580 -0.018168   
1 -0.024376  0.019182  0.079968  0.048837 -0.071362  0.033691 -0.052863   
2 -0.038274  0.015284  0.091118  0.007086  0.020357  0.019580 -0.018168   
3 -0.024376  0.019182  0.079968  0.048837 -0.071362  0.033691 -0.052863   
4 -0.007769 -0.022311  0.094439 -0.009006 -0.005161  0.060440  0.001238   

        7         8         9      ...          502       503       504  \
0  0.030250  0.034157  0.054213    ...     0.039918 -0.080380  0.053053   
1 -0.002503  0.052732  0.009590    ...     0.038410 -0.079658  0.062860   
2  0.030250  0.034157  0.054213    ...     0.039918 -0.080380  0.053053   
3 -0.002503  0.052732  0.009590    ...     0.038410 -0.079658  0.062860   
4 -0.014119 -0.000499  0.032608    ...     0.026762 -0.085583  0.062254   

        505       506       507       508       509       510       511  
0  0.021043 -0.017571  0.032146  0.037611 -0.026567  0.026762 -0.006932  
1  0.052881 -0.000144  0.050155 -0.000216 -0.053850  0.021004  0.039227  
2  0.021043 -0.017571  0.032146  0.037611 -0.026567  0.026762 -0.006932  
3  0.052881 -0.000144  0.050155 -0.000216 -0.053850  0.021004  0.039227  
4  0.018541 -0.048938  0.051146 -0.011664 -0.025159 -0.020737  0.016050  

[5 rows x 512 columns]

In [110]:
# Confirm the final output is a dataframe
type(final_data)

pandas.core.frame.DataFrame

In [90]:
# Add in the class column to the dataframe and print to confirm 
final_data['Class']=qs.Class
final_data.head()

0         1         2         3         4         5         6  \
0 -0.038274  0.015284  0.091118  0.007086  0.020357  0.019580 -0.018168   
1 -0.024376  0.019182  0.079968  0.048837 -0.071362  0.033691 -0.052863   
2 -0.038274  0.015284  0.091118  0.007086  0.020357  0.019580 -0.018168   
3 -0.024376  0.019182  0.079968  0.048837 -0.071362  0.033691 -0.052863   
4 -0.007769 -0.022311  0.094439 -0.009006 -0.005161  0.060440  0.001238   

          7         8         9  ...         503       504       505  \
0  0.030250  0.034157  0.054213  ...   -0.080380  0.053053  0.021043   
1 -0.002503  0.052732  0.009590  ...   -0.079658  0.062860  0.052881   
2  0.030250  0.034157  0.054213  ...   -0.080380  0.053053  0.021043   
3 -0.002503  0.052732  0.009590  ...   -0.079658  0.062860  0.052881   
4 -0.014119 -0.000499  0.032608  ...   -0.085583  0.062254  0.018541   

        506       507       508       509       510       511  Class  
0 -0.017571  0.032146  0.037611 -0.026567  0.026762 -0.006932    1.0  
1 -0.000144  0.050155 -0.000216 -0.053850  0.021004  0.039227    1.0  
2 -0.017571  0.032146  0.037611 -0.026567  0.026762 -0.006932    1.0  
3 -0.000144  0.050155 -0.000216 -0.053850  0.021004  0.039227    1.0  
4 -0.048938  0.051146 -0.011664 -0.025159 -0.020737  0.016050    1.0  

[5 rows x 513 columns]

In [134]:
# I was getting some painful errors that I couldn't train my model with NaNs so I just deleted those indexes
final_data_model = final_data.drop(final_data.index[99:101])

### Q2: Take your numbers from Q1 and create 2 classifiers of any type.  What is your best guess for the accuracy of your models. (Don't forget to use good data science practices!)

#### Set global variables

In [136]:
# Set variables for X and y
X = final_data_model.drop('Class', axis=1)
y = final_data_model['Class']

In [178]:
# Define train test splits 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

#### Experinent with SVM Classifier

In [179]:
# Import SVM 
from sklearn.svm import SVC
svc_classifier = SVC(kernel='linear')

In [189]:
# Fit the SVM model
svc_classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [181]:
# Run the predictions for the SVM
y_pred_svc = svc_classifier.predict(X_test)

In [190]:
# Import model evaluation packages
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

In [191]:
# Print results for the SVM
print("The accuracy of the SVM model is:",metrics.accuracy_score(y_test, y_pred_svc))
print(confusion_matrix(y_test,y_pred_svc))
print(classification_report(y_test,y_pred_svc))

The accuracy of the SVM model is: 0.9
[[11  2]
 [ 0  7]]
             precision    recall  f1-score   support

        1.0       1.00      0.85      0.92        13
        2.0       0.78      1.00      0.88         7

avg / total       0.92      0.90      0.90        20



#### Experiment with Random Forest Classifier

In [184]:
# Import the random forest model
from sklearn.ensemble import RandomForestClassifier

In [185]:
random_forest_classifier = RandomForestClassifier(n_estimators=100)

In [186]:
# Train the model 
random_forest_classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [187]:
# Run the predictions
y_pred_rf = random_forest_classifier.predict(X_test)

In [188]:
# Print the results of the random forest model 
print("The accuracy of the random forest model is:",metrics.accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))

The accuracy of the random forest model is: 0.95
[[12  1]
 [ 0  7]]
             precision    recall  f1-score   support

        1.0       1.00      0.92      0.96        13
        2.0       0.88      1.00      0.93         7

avg / total       0.96      0.95      0.95        20



I experimented with both the SVM and Random Forest Ensemble classifiers. Of both models, the random forets model performed better with an accuracy of 95% whereas the SVM classifier performed at an accuracy of 90%.